#### 1. Write a function, foo_1, that takes a NumPy array `arr` and returns the indices of the elements that are closest to a given target. If target is not in the given array, it should return ‘no item found’

In [2]:
import numpy as np

In [57]:
def foo_1(arr, target):
    if target not in arr:
        return 'no item found'
    else:
        return np.argsort(np.abs(arr - target))

arr = np.array([3, 8, 7, 7, 7, 7, 7, 8, 7, 10])
target = 7

r = foo_1(arr, target)
print(r)

[2 3 4 5 6 8 1 7 9 0]


In [61]:
target = 11

foo_1(arr, target)

'no item found'

#### 2. Write a user defined function foo_2 that takes a 1 or 2 dim NumPy array arr and returns a new n-1 dim array, where each element is replaced by the without using count of non-zero elements wrt axis.


In [3]:
def foo_2(arr, axis=0):
 
    if arr.ndim not in [2,3]:
        raise ValueError("Input array must be 2 or 3 dimensional.")

    return np.count_nonzero(arr, axis=axis)

arr = np.array([[1, 2, 3, 4],
                [0, 5, 0, 0],
                [2, 0, 1, 0]])

r = foo_2(arr, axis = 0)
print(r)

[2 2 2 1]


In [4]:
r = foo_2(arr, axis = 1)
print(r)

[4 1 2]


In [5]:
def foo_3(arr, axis=0):
 
    if arr.ndim not in [2,3]:
        raise ValueError("Input array must be 2 or 3 dimensional.")

    return np.count_nonzero(arr, axis=axis)


In [6]:
arr = np.array([[[1, 2, 3, 4],[0, 5, 0, 0],[2, 0, 1, 0]],
                [[2, 0, 1, 0],[0, 5, 0, 0],[1, 2, 3, 4]]])
r = foo_3(arr , axis = 0)
print(r)

[[2 1 2 1]
 [0 2 0 0]
 [2 1 2 1]]


In [7]:
r = foo_3(arr , axis = 1)
print(r)

[[2 2 2 1]
 [2 2 2 1]]


In [8]:
r = foo_3(arr , axis = 2)
print(r)

[[4 1 2]
 [2 1 4]]


#### 3) 
#### 3.1 You are given a 2D NumPy array of data representing student scores. Each row represents a student, and each column represents a subject. Extract the scores of all students who scored above 90 in at least one subject. Provide the resulting array.


In [12]:
data = np.array([[85, 89, 88],
                 [78, 89, 94],
                 [91, 87, 90],
                 [87, 95, 84]])

marks = np.any(data > 90, axis=1)
result = data[ marks]

print("Students scored above 90 : ", result, sep='\n')

Students scored above 90 : 
[[78 89 94]
 [91 87 90]
 [87 95 84]]


#### 3.2 You are provided with a 2D NumPy array of data representing sales data for different products. Each row corresponds to a product, and each column represents the monthly sales for a specific month. Calculate the following statistics for each product: mean, median, standard deviation, and the month with the highest sales.

In [14]:
data = np.array([[120,150,130,110],
                 [200,180,220,250],
                 [90,100,95,110],
                 [300,280,320,340]])

In [15]:
def foo(data):
    mean_values = np.mean(data, axis=1)
    median_values = np.median(data, axis=1)
    std_dev_values = np.std(data, axis=1)
    highest_sales_monthly = np.max(data, axis=1)
    
    for i in range(len(data)):
        print(f"Product {i + 1}:")
        print(f"Mean: {mean_values[i]}")
        print(f"Median: {median_values[i]}")
        print(f"Standard Deviation: {std_dev_values[i]}")
        print(f"Month with Highest Sales: Month {highest_sales_monthly[i] + 1}")
        print()
        
foo(data)

Product 1:
Mean: 127.5
Median: 125.0
Standard Deviation: 14.79019945774904
Month with Highest Sales: Month 151

Product 2:
Mean: 212.5
Median: 210.0
Standard Deviation: 25.8602010819715
Month with Highest Sales: Month 251

Product 3:
Mean: 98.75
Median: 97.5
Standard Deviation: 7.39509972887452
Month with Highest Sales: Month 111

Product 4:
Mean: 310.0
Median: 310.0
Standard Deviation: 22.360679774997898
Month with Highest Sales: Month 341



#### 3.3 Create a NumPy array of size 1000 with random integers between 1 and 100. Then, use NumPy functions to find the top 10 most frequently occurring values in the array.



In [63]:
a = np.random.randint(1,100,1000)

unique_values, value_counts = np.unique(a, return_counts=True)
indices = np.argsort(value_counts)[::-1][:10]

values = unique_values[indices]
counts = value_counts[indices]

for value, count in zip(values, counts):
    print(f"{value: }   {count: }")

 33    18
 31    17
 91    16
 53    15
 92    15
 79    15
 41    14
 84    14
 63    14
 76    14
